/* Generated by Yosys 0.32+63 (git sha1 86df114a3, gcc 11.4.0-1ubuntu1~22.04 -fPIC -Os) */

module blocking_caveat(a, b, c, d);
  wire _0_;
  input a;
  wire a;
  input b;
  wire b;
  input c;
  wire c;
  output d;
  wire d;
  assign _0_ = ~(b | a);
  assign d = c & ~(_0_);
endmodule
