/* Generated by Yosys 0.32+63 (git sha1 86df114a3, gcc 11.4.0-1ubuntu1~22.04 -fPIC -Os) */

module ternary_operator_mux(i0, i1, sel, y);
  input i0;
  wire i0;
  input i1;
  wire i1;
  input sel;
  wire sel;
  output y;
  wire y;
  assign y = sel ? i1 : i0;
endmodule
